*&---------------------------------------------------------------------*
*& Report  ZSHASHANK2
*&
*&---------------------------------------------------------------------*
*&
*&
*&---------------------------------------------------------------------*

REPORT  ZSHASHANK2.

* USING FIELD-STRINGS.

*DATA : BEGIN OF HI,
*      STUDID TYPE ZSTUDID,
*      STUDENTNAME TYPE ZSTUNAME,
*      CITY TYPE ORT01,
*      END OF HI.
*
*SELECT STUDID STUDENTNAME CITY FROM ZSTUDENTS INTO HI.
*  WRITE:/  HI.
* ENDSELECT.

"WRITE HI.
*WRITE : / FS-STUDID, FS-STUDENTNAME, FS-CITY.

* INTERNAL TABLES USING OCCURS CLAUSE

*DATA : BEGIN OF ITAB OCCURS 0, "
*      STUDID TYPE ZSTUDID,
*      STUDENTNAME TYPE ZSTUNAME,
*      CITY TYPE ORT01,
*      END OF ITAB.
*
*SELECT STUDID STUDENTNAME CITY FROM ZSTUDENTS INTO ITAB.
*  APPEND ITAB.
* ENDSELECT.
*
* LOOP AT ITAB.
*"WRITE : / ITAB.
* WRITE : / ITAB-STUDID, ITAB-STUDENTNAME, ITAB-CITY.
*
* ENDLOOP.


* INTERNAL TABLE USING TYPE STRUCTURE.

*TYPES:BEGIN OF TY, "
*      STUDID TYPE ZSTUDID,
*      STUDENTNAME TYPE ZSTUNAME,
*      CITY TYPE ORT01,
*      END OF TY.
*
*DATA: ITAB TYPE TABLE OF TY,
*      WA LIKE LINE OF ITAB.
*
*SELECT STUDID STUDENTNAME CITY FROM ZSTUDENTS INTO TABLE ITAB.
*
*  LOOP AT ITAB INTO WA.
*
*    WRITE : / WA-STUDID, WA-STUDENTNAME, WA-CITY.
*
* ENDLOOP.

TYPE-POOLS: ZTY.


DATA: ITAB TYPE TABLE OF ZTY_TY,
      WA LIKE LINE OF ITAB.

SELECT STUDID STUDENTNAME CITY FROM ZSTUDENTS INTO TABLE ITAB.

  LOOP AT ITAB INTO WA.

    WRITE : / WA-STUDID, WA-STUDENTNAME, WA-CITY.

 ENDLOOP.
